#TODO: this is hard coded but I would love to have it accessable in the UI so that if any changes to the methoid are made it could be easily changed without changing the code.
'''blockNameDictionary = {
        'Equilibration': 'Equilibration',
        'Elution': 'Elution',
        'Wash_1': 'Wash 1',
        'Col_Wash_1': 'Wash 1',
        'Wash_3': 'Wash 3',
        'Col_Wash_3': 'Wash 3',
        'Charge': 'Charge',
        'Storage': 'Storage',
        'Regeneration': 'Regeneration',
        'Regen': 'Regeneration',
        'Col_Regen': 'Regeneration',
        'Pre_Sanitization': 'Pre Sanitization',
        'Pre_Sani_Rinse':'Pre Sanitization Rinse',
        'Rinse_1':'Post Sanitization Rinse',
        'Rinse_2': 'Post Sanitization Rinse 2',
        'Post_Use_Sanitization': 'Post Sanitization',
        'Clean_1': 'Post Sanitization',
        'Clean_2': 'Post Sanitization',
        'Rinse_3': 'Post Sanitization Rinse',
        'Rinse_4': 'Post Sanitization Rinse 2',
        'Storage_Rinse': 'Storage Rinse',
        'Wash_2': 'Wash 2',
        'Col_Wash_2': 'Wash 2',
        'Pre_Use_Clean_1': 'Pre Sanitization',
        'Pre_Use_Clean_2': 'Pre Sanitization 2',
        'Pre_Use_Rinse_1' :'Pre Sanitization Rinse', 
        'Pre_Use_Rinse_2' :'Pre Sanitization Rinse 2', 
        'first_cv_equil_flowrate': "Pre Sanitization Rinse", 
        'Flush_Skid_Inlet_2_Elution': "Elution", 
        'Wash_2_System_Flush': "Wash 2"

    }'''